/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exstopwatch;

import static java.lang.Thread.sleep;

/**
 *
 * @author Dell
 */
public class countdown extends javax.swing.JFrame {
private int hour;
private int minute;
private int second;
private int csecond;
private boolean isStart;
    int count=0;
    String str;
    public countdown() {
        initComponents();
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
        panel.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        hour1 = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        sec = new javax.swing.JLabel();
        csec = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cancel = new javax.swing.JLabel();
        p1 = new javax.swing.JLabel();
        record = new javax.swing.JLabel();
        reset = new javax.swing.JLabel();
        start = new javax.swing.JLabel();
        pause = new javax.swing.JLabel();
        p5 = new javax.swing.JLabel();
        p4 = new javax.swing.JLabel();
        p3 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 100));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setForeground(new java.awt.Color(153, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("COUNTDOWN TIMER");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 250, 30));

        hour1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        hour1.setForeground(new java.awt.Color(255, 255, 255));
        hour1.setText("00");
        jPanel1.add(hour1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 90, -1));

        min.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        min.setForeground(new java.awt.Color(255, 255, 255));
        min.setText("00");
        jPanel1.add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 210, 90, -1));

        sec.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        sec.setForeground(new java.awt.Color(255, 255, 255));
        sec.setText("00");
        jPanel1.add(sec, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 100, -1));

        csec.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        csec.setForeground(new java.awt.Color(255, 255, 255));
        csec.setText("00");
        jPanel1.add(csec, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 80, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Hour");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 60, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Min");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 50, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Sec");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, -1));

        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exstopwatch/icons8_Delete_30px.png"))); // NOI18N
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancelMousePressed(evt);
            }
        });
        jPanel1.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, -1, -1));

        p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exstopwatch/icons8_Delete_30px_1.png"))); // NOI18N
        p1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                p1MousePressed(evt);
            }
        });
        jPanel1.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, -1, -1));

        record.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exstopwatch/icons8_Pencil_30px.png"))); // NOI18N
        record.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                recordMousePressed(evt);
            }
        });
        jPanel1.add(record, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exstopwatch/icons8_Synchronize_30px.png"))); // NOI18N
        reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                resetMousePressed(evt);
            }
        });
        jPanel1.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));

        start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exstopwatch/icons8_Play_30px.png"))); // NOI18N
        start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                startMousePressed(evt);
            }
        });
        jPanel1.add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, -1, -1));

        pause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exstopwatch/icons8_Pause_30px_1.png"))); // NOI18N
        pause.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pauseMousePressed(evt);
            }
        });
        jPanel1.add(pause, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, -1, -1));

        p5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exstopwatch/icons8_Pencil_30px_1.png"))); // NOI18N
        p5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                p5MousePressed(evt);
            }
        });
        jPanel1.add(p5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        p4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exstopwatch/icons8_Synchronize_30px_1.png"))); // NOI18N
        p4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                p4MousePressed(evt);
            }
        });
        jPanel1.add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));

        p3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exstopwatch/icons8_Play_30px_1.png"))); // NOI18N
        p3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                p3MousePressed(evt);
            }
        });
        jPanel1.add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, -1, -1));

        p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exstopwatch/icons8_Pause_30px_2.png"))); // NOI18N
        p2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                p2MousePressed(evt);
            }
        });
        jPanel1.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exstopwatch/2.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 490, 120));

        jLabel1.setBackground(new java.awt.Color(153, 204, 255));
        jLabel1.setForeground(new java.awt.Color(153, 153, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exstopwatch/1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 450, 240));

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text.setColumns(20);
        text.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        text.setRows(5);
        text.setBorder(null);
        jScrollPane1.setViewportView(text);

        panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 130));

        jPanel1.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 450, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void list()
{
   count++;
        str+="\n"+count+"]"+hour1.getText()+":"+min.getText()+":"+sec.getText()+":"+csec.getText()+"\n";
        text.setText(str);
}

    private void recordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recordMousePressed
        p5.setVisible(true);
        record.setVisible(false);
        panel.setVisible(true);
        list();
        
    }//GEN-LAST:event_recordMousePressed

    private void resetMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMousePressed
        p4.setVisible(true);
        reset.setVisible(false);
        isStart=false;
        csecond=0;
        second=0;
        minute=0;
        hour=0;
        hour1.setText("0"+hour);
        min.setText("0"+minute);
        sec.setText("0"+second);
        csec.setText("0"+csecond);
        
    }//GEN-LAST:event_resetMousePressed

    private void startMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMousePressed
         p3.setVisible(true);
        start.setVisible(false);
         pause.setVisible(true); 
         p2.setVisible(false);
         p4.setVisible(false);
         reset.setVisible(true);
         
         isStart=true;
         
         Thread th=new Thread()
         {
            public void run()
            {
                
                while(isStart==true)
                {
                    try
                    {
                        sleep(100);
                    
                    csecond++;
                    if(csecond==100)
                    {
                        second++;
                        csecond=0;
                    }
                    if(second==60)
                    {
                        minute++;
                        second=0;
                    }
                    if(minute==60)
                    {
                        hour++;
                        minute=0;
                    }
                    hour1.setText("0"+hour);
                    min.setText("0"+minute);
                    sec.setText("0"+second);
                    csec.setText(""+csecond);
                    }
                    catch(Exception ex)
                    {
                        System.out.print("something is wrong");
                    }
                }
            }
         };th.start();
         
      
         
    }//GEN-LAST:event_startMousePressed

    private void pauseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pauseMousePressed
       p2.setVisible(true);
        pause.setVisible(false);
        start.setVisible(true);
        p3.setVisible(false);
        p4.setVisible(false);
         reset.setVisible(true);
         
         isStart=false;
    }//GEN-LAST:event_pauseMousePressed

    private void cancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMousePressed
        p1.setVisible(true);
        cancel.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_cancelMousePressed

    private void p1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1MousePressed
       cancel.setVisible(true);
       System.exit(0);
    }//GEN-LAST:event_p1MousePressed

    private void p2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p2MousePressed
      pause.setVisible(true); 
      
      
    }//GEN-LAST:event_p2MousePressed

    private void p3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p3MousePressed
         start.setVisible(true);
        
    }//GEN-LAST:event_p3MousePressed

    private void p4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p4MousePressed
       reset.setVisible(true);
    }//GEN-LAST:event_p4MousePressed

    private void p5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p5MousePressed
        record.setVisible(true);
        panel.setVisible(false);
    }//GEN-LAST:event_p5MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(countdown.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(countdown.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(countdown.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(countdown.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new countdown().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cancel;
    private javax.swing.JLabel csec;
    private javax.swing.JLabel hour1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel min;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel p3;
    private javax.swing.JLabel p4;
    private javax.swing.JLabel p5;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel pause;
    private javax.swing.JLabel record;
    private javax.swing.JLabel reset;
    private javax.swing.JLabel sec;
    private javax.swing.JLabel start;
    private javax.swing.JTextArea text;
    // End of variables declaration//GEN-END:variables
}
